# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - run: actions/setup-node@v4
      - run: actions/checkout@v4
      - run: npm ci
      - run: node src\server.mjs
